# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from AutoScriptor.control.NemuIpc.device.method.nemu_ipc import RequestHumanTakeover
from AutoScriptor.core import *
from AutoScriptor.core.background import bg
from AutoScriptor.crypto.update_config import set_config, verify_config
from AutoScriptor.utils.box import Box
from AutoScriptor.utils.constant import cfg
from AutoScriptor.utils.ui_map import ui

__all__ = ['Box', 'Target', 'ui', 'B', 'I', 'T', 'cfg', 'click', 'locate', 'input', 'get_colors', 'edit_img', 'swipe', 'ui_T', 'ui_F', 'ui_idx', 'key_event', 'wait_for_appear', 'wait_for_disappear', 'first', 'simple', 'full', 'count', 'switch_base', 'sleep', 'extract_info', 'bg', 'mixctrl', 'set_config', 'verify_config', 'RequestHumanTakeover']

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import _frozen_importlib_external
import json
import ntpath
import warnings
import typing
import logzero
import logzero.logger
import time
import cv2
import numpy
import adbutils
import adbutils.adb
import threading
import random
import pyscrcpy
import subprocess
import re
import functools
import MumuAdaptor
import MumuAdaptor.loggings
import MumuAdaptor.loggings.logger
import datetime
import PIL
import PIL.Image
import collections
import collections.deque
import string
import yaml
import ctypes
import sys
import AutoScriptor.control.NemuIpc.base.utils.ensure_time
import AutoScriptor.control.NemuIpc.base.utils.random_rectangle_point
import socket
import uiautomator2
import uiautomator2cache
import adbutils.AdbTimeout
import lxml
import lxml.etree
import adbutils._AdbStreamConnection
import adbutils.AdbConnection
import traceback
import getpass
import logzero.logfile
import collections.abc
import abc
import numpy.ndarray
import copy
import secrets
import cryptography
import cryptography.hazmat
import cryptography.hazmat.primitives
import cryptography.hazmat.primitives.ciphers
import cryptography.hazmat.primitives.ciphers.aead
import cryptography.hazmat.primitives.hashes
import cryptography.hazmat.primitives.kdf
import cryptography.hazmat.primitives.kdf.pbkdf2
import base64
import hmac
import hashlib
import paddleocr
import paddleocr.PaddleOCR
import fuzzywuzzy
import fuzzywuzzy.fuzz
import paddle
import concurrent
import concurrent.futures
import concurrent.futures.ThreadPoolExecutor
import concurrent.futures.as_completed
import tkinter
import tkinter.filedialog
import tkinter.messagebox
import PIL.ImageTk
import pypinyin
import pypinyin.lazy_pinyin
import pandas
import questionary
import shutil
import csv